# Generated by Django 5.2.17 on 2026-09-18 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.driving.models


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FatigueSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.driving.models.fatigue_snapshot_path)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='snapshot', to='driving.fatigueevent')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_snapshots', to='driving.drivingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatigue_snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
